spring:
 datasource:
  url: jdbc:sqlserver://myemployeeserver.database.windows.net:1433;database=EmployeeServer;user=sonusainicse@myemployeeserver;password={Sksaini@0798};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  username: sonusainicse
  password: Sksaini@0798
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   dialect: org.hibernate.dialect.SQLServer2012Dialect
   
server:
 port: 8081